"""HTML report generation for baseline evaluation."""

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .baseline import BaselineResult


def generate_html_report(result: "BaselineResult", output_path: Path) -> None:
    """Generate interactive HTML baseline evaluation report.

    Creates self-contained HTML with embedded CSS/JS for:
    - Metrics summary cards
    - Filter/sort controls
    - Side-by-side comparison table
    - Expandable detail views
    - Responsive mobile-friendly design

    Args:
        result: BaselineResult with metrics and comparison examples
        output_path: Path to save HTML file
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Build comparison cards
    comparison_cards = _build_comparison_cards(result.examples)

    # Build metrics cards
    metrics_cards = _build_metrics_cards(result.metrics)

    # Build full HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NanoDistill Baseline Evaluation: {result.run_name}</title>
    <style>
        {_get_embedded_css()}
    </style>
</head>
<body>
    <div class="container">
        <!-- Branding -->
        <div class="nanodistill-branding">
            <div class="branding-content">
                <div class="branding-logo">📚</div>
                <div class="branding-text">
                    <div class="branding-name">NanoDistill</div>
                    <div class="branding-tagline">
                        Knowledge distillation for small language models
                    </div>
                </div>
            </div>
        </div>

        <!-- Header -->
        <header class="header">
            <div class="header-content">
                <h1>🔬 Baseline Evaluation Report</h1>
                <p class="run-name">
                    Model: <strong>{result.run_name}</strong>
                </p>
                <p class="timestamp">
                    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
                </p>
            </div>
        </header>

        <!-- Metrics Summary -->
        <section class="metrics-section">
            <h2>Performance Summary</h2>
            <div class="metrics-grid">
                {metrics_cards}
            </div>
        </section>

        <!-- Controls -->
        <section class="controls-section">
            <h2>Filter Examples</h2>
            <div class="button-group">
                <button class="btn btn-primary" onclick="filterExamples('all')">
                    ✓ All ({len(result.examples)})
                </button>
                <button class="btn btn-success" onclick="filterExamples('matches')">
                    ✓ Exact Matches ({sum(1 for e in result.examples if e.exact_match)})
                </button>
                <button class="btn btn-danger" onclick="filterExamples('mismatches')">
                    ✗ Mismatches ({sum(1 for e in result.examples if not e.exact_match)})
                </button>
            </div>
        </section>

        <!-- Comparisons -->
        <section class="comparisons-section">
            <h2>Example Comparisons</h2>
            <div id="comparisons-container">
                {comparison_cards}
            </div>
        </section>

        <!-- Footer -->
        <footer class="footer">
            <p>
                Generated by <strong>NanoDistill</strong> Baseline Evaluator
            </p>
            <p class="footer-tagline">
                Knowledge distillation for small language models on Apple Silicon
            </p>
        </footer>
    </div>

    <script>
        {_get_embedded_js()}
    </script>
</body>
</html>
"""

    output_path.write_text(html)


def _get_embedded_css() -> str:
    """Return embedded CSS styles."""
    return """
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    :root {
        --primary: #2563eb;
        --primary-hover: #1d4ed8;
        --success: #16a34a;
        --success-hover: #15803d;
        --danger: #dc2626;
        --danger-hover: #b91c1c;
        --warning: #d97706;
        --gray-50: #f9fafb;
        --gray-100: #f3f4f6;
        --gray-200: #e5e7eb;
        --gray-300: #d1d5db;
        --gray-400: #9ca3af;
        --gray-600: #4b5563;
        --gray-700: #374151;
        --gray-900: #111827;
        --border-radius: 8px;
        --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
        --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
    }

    body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
            "Helvetica Neue", Arial, sans-serif;
        background-color: var(--gray-50);
        color: var(--gray-900);
        line-height: 1.6;
    }

    .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
    }

    /* NanoDistill Branding */
    .nanodistill-branding {
        background: linear-gradient(135deg, rgba(37, 99, 235, 0.05) 0%,
            rgba(59, 130, 246, 0.05) 100%);
        border: 1px solid rgba(37, 99, 235, 0.1);
        border-radius: var(--border-radius);
        padding: 15px 20px;
        margin-bottom: 30px;
    }

    .branding-content {
        display: flex;
        align-items: center;
        gap: 12px;
    }

    .branding-logo {
        font-size: 1.8em;
    }

    .branding-text {
        display: flex;
        flex-direction: column;
        gap: 2px;
    }

    .branding-name {
        font-size: 1.1em;
        font-weight: 700;
        color: var(--primary);
    }

    .branding-tagline {
        font-size: 0.85em;
        color: var(--gray-600);
        font-weight: 500;
    }

    /* Header */
    .header {
        background: linear-gradient(135deg, var(--primary) 0%, #1e40af 100%);
        color: white;
        padding: 40px 20px;
        border-radius: var(--border-radius);
        margin-bottom: 40px;
        box-shadow: var(--shadow-lg);
    }

    .header-content h1 {
        font-size: 2.5em;
        margin-bottom: 10px;
    }

    .run-name, .timestamp {
        font-size: 0.95em;
        opacity: 0.95;
    }

    .timestamp {
        margin-top: 5px;
        font-size: 0.85em;
        opacity: 0.85;
    }

    /* Metrics Section */
    .metrics-section h2,
    .controls-section h2,
    .comparisons-section h2 {
        font-size: 1.5em;
        margin-bottom: 20px;
        color: var(--gray-900);
    }

    .metrics-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        gap: 20px;
        margin-bottom: 40px;
    }

    .metric-card {
        background: white;
        padding: 20px;
        border-radius: var(--border-radius);
        box-shadow: var(--shadow-md);
        text-align: center;
        border-left: 4px solid var(--primary);
    }

    .metric-card h3 {
        font-size: 0.9em;
        color: var(--gray-600);
        font-weight: 500;
        margin-bottom: 10px;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }

    .metric-value {
        font-size: 2em;
        font-weight: bold;
        color: var(--primary);
    }

    .metric-subtitle {
        font-size: 0.85em;
        color: var(--gray-400);
        margin-top: 8px;
    }

    /* Controls Section */
    .controls-section {
        background: white;
        padding: 20px;
        border-radius: var(--border-radius);
        box-shadow: var(--shadow-md);
        margin-bottom: 40px;
    }

    .button-group {
        display: flex;
        gap: 10px;
        flex-wrap: wrap;
    }

    .btn {
        padding: 10px 20px;
        border: none;
        border-radius: var(--border-radius);
        font-size: 0.95em;
        font-weight: 500;
        cursor: pointer;
        transition: all 0.2s;
        box-shadow: var(--shadow-sm);
    }

    .btn:hover {
        transform: translateY(-2px);
        box-shadow: var(--shadow-md);
    }

    .btn-primary {
        background-color: var(--primary);
        color: white;
    }

    .btn-primary:hover {
        background-color: var(--primary-hover);
    }

    .btn-success {
        background-color: var(--success);
        color: white;
    }

    .btn-success:hover {
        background-color: var(--success-hover);
    }

    .btn-danger {
        background-color: var(--danger);
        color: white;
    }

    .btn-danger:hover {
        background-color: var(--danger-hover);
    }

    /* Comparisons Section */
    .comparisons-section {
        margin-bottom: 40px;
    }

    .comparison-card {
        background: white;
        border-radius: var(--border-radius);
        box-shadow: var(--shadow-md);
        margin-bottom: 20px;
        overflow: hidden;
        transition: box-shadow 0.2s;
    }

    .comparison-card:hover {
        box-shadow: var(--shadow-lg);
    }

    .comparison-card.match {
        border-left: 4px solid var(--success);
    }

    .comparison-card.mismatch {
        border-left: 4px solid var(--danger);
    }

    .comparison-header {
        padding: 15px 20px;
        background-color: var(--gray-100);
        cursor: pointer;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .comparison-header:hover {
        background-color: var(--gray-200);
    }

    .comparison-title {
        font-weight: 600;
        flex: 1;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .comparison-badge {
        display: inline-block;
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 0.8em;
        font-weight: 500;
        margin-left: 15px;
    }

    .match-badge {
        background-color: #d1fae5;
        color: #065f46;
    }

    .mismatch-badge {
        background-color: #fee2e2;
        color: #7f1d1d;
    }

    .similarity-badge {
        background-color: var(--gray-200);
        color: var(--gray-700);
    }

    .toggle-arrow {
        margin-left: 15px;
        font-size: 1.2em;
        transition: transform 0.2s;
    }

    .toggle-arrow.open {
        transform: rotate(180deg);
    }

    .comparison-content {
        display: none;
        padding: 20px;
    }

    .comparison-content.open {
        display: block;
    }

    .comparison-section-title {
        font-weight: 600;
        margin-top: 15px;
        margin-bottom: 10px;
        color: var(--gray-700);
        font-size: 0.9em;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }

    .comparison-text {
        background-color: var(--gray-50);
        padding: 12px;
        border-radius: 4px;
        border-left: 3px solid var(--gray-300);
        font-family: "Monaco", "Menlo", monospace;
        font-size: 0.9em;
        line-height: 1.5;
        word-break: break-word;
        max-height: 200px;
        overflow-y: auto;
    }

    .comparison-text.empty {
        color: var(--gray-400);
        font-style: italic;
    }

    .comparison-input {
        background-color: var(--gray-50);
        padding: 12px;
        border-radius: 4px;
        border-left: 3px solid var(--primary);
        font-family: "Monaco", "Menlo", monospace;
        font-size: 0.9em;
        word-break: break-word;
    }

    .diff-table {
        width: 100%;
        border-collapse: collapse;
        font-family: "Monaco", "Menlo", monospace;
        font-size: 0.85em;
    }

    .diff-table td {
        padding: 8px;
        border: 1px solid var(--gray-200);
    }

    .diff-table .diff_header {
        background-color: var(--gray-200);
        font-weight: 600;
    }

    .diff-table .diff_add {
        background-color: #d1fae5;
    }

    .diff-table .diff_sub {
        background-color: #fee2e2;
    }

    .comparison-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 20px;
        margin-top: 15px;
    }

    .comparison-grid-3col {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        gap: 20px;
        margin-top: 15px;
    }

    .model-label {
        font-weight: 600;
        margin-bottom: 8px;
        color: var(--gray-700);
        font-size: 0.9em;
    }

    .metric-small {
        font-size: 0.8em;
        color: var(--gray-600);
        margin-top: 8px;
    }

    /* Field Comparison Section */
    .field-comparison-container {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 20px;
        margin-top: 15px;
    }

    .field-group {
        background-color: var(--gray-50);
        border: 1px solid var(--gray-200);
        border-radius: var(--border-radius);
        padding: 12px;
    }

    .field-group-title {
        font-weight: 600;
        font-size: 0.9em;
        color: var(--gray-700);
        margin-bottom: 10px;
        padding-bottom: 8px;
        border-bottom: 2px solid var(--gray-200);
    }

    .field-row {
        padding: 6px 8px;
        margin-bottom: 6px;
        border-radius: 4px;
        font-size: 0.85em;
        font-family: "Monaco", "Menlo", monospace;
    }

    .field-match {
        background-color: #d1fae5;
        color: #065f46;
        border-left: 3px solid var(--success);
    }

    .field-mismatch {
        background-color: #fee2e2;
        color: #7f1d1d;
        border-left: 3px solid var(--danger);
    }

    .field-name {
        font-weight: 500;
        margin-left: 8px;
    }

    @media (max-width: 1024px) {
        .comparison-grid-3col {
            grid-template-columns: 1fr 1fr;
        }

        .field-comparison-container {
            grid-template-columns: 1fr;
        }
    }

    @media (max-width: 768px) {
        .branding-content {
            flex-direction: column;
            gap: 8px;
        }

        .branding-logo {
            font-size: 1.5em;
        }

        .branding-name {
            font-size: 1em;
        }

        .branding-tagline {
            font-size: 0.8em;
        }

        .header-content h1 {
            font-size: 1.8em;
        }

        .metrics-grid {
            grid-template-columns: 1fr;
        }

        .button-group {
            flex-direction: column;
        }

        .btn {
            width: 100%;
        }

        .comparison-grid {
            grid-template-columns: 1fr;
        }

        .comparison-grid-3col {
            grid-template-columns: 1fr;
        }

        .field-comparison-container {
            grid-template-columns: 1fr;
        }

        .comparison-header {
            flex-direction: column;
            align-items: flex-start;
        }

        .comparison-badge {
            margin-left: 0;
            margin-top: 10px;
        }
    }

    /* Footer */
    .footer {
        text-align: center;
        color: var(--gray-600);
        font-size: 0.9em;
        margin-top: 60px;
        padding-top: 20px;
        border-top: 1px solid var(--gray-200);
    }

    .footer-tagline {
        font-size: 0.85em;
        color: var(--gray-400);
        margin-top: 8px;
        font-style: italic;
    }

    /* Hidden by filter */
    .hidden {
        display: none;
    }
"""


def _get_embedded_js() -> str:
    """Return embedded JavaScript for interactivity."""
    return """
    let currentFilter = 'all';

    function filterExamples(filter) {
        currentFilter = filter;
        const cards = document.querySelectorAll('.comparison-card');

        cards.forEach(card => {
            const isMatch = card.classList.contains('match');

            if (filter === 'all') {
                card.classList.remove('hidden');
            } else if (filter === 'matches' && isMatch) {
                card.classList.remove('hidden');
            } else if (filter === 'mismatches' && !isMatch) {
                card.classList.remove('hidden');
            } else {
                card.classList.add('hidden');
            }
        });

        // Update button states
        document.querySelectorAll('.button-group .btn').forEach(btn => {
            btn.classList.remove('btn-primary');
            btn.classList.add('btn-primary');
        });
    }

    function toggleDetails(id) {
        const content = document.getElementById('content-' + id);
        const arrow = document.getElementById('arrow-' + id);

        if (content) {
            content.classList.toggle('open');
            if (arrow) {
                arrow.classList.toggle('open');
            }
        }
    }

    // Initialize: show all on load
    document.addEventListener('DOMContentLoaded', () => {
        filterExamples('all');
    });
"""


def _build_metrics_cards(metrics) -> str:
    """Build HTML for metrics cards."""
    cards = f"""
        <div class="metric-card">
            <h3>Exact Match Rate</h3>
            <div class="metric-value">{metrics.exact_match_rate:.1%}</div>
            <div class="metric-subtitle">
                {metrics.exact_matches}/{metrics.total_examples} examples
            </div>
        </div>

        <div class="metric-card">
            <h3>Avg Similarity</h3>
            <div class="metric-value">{metrics.avg_similarity:.2f}</div>
            <div class="metric-subtitle">Character 3-gram Jaccard</div>
        </div>

        <div class="metric-card">
            <h3>Total Examples</h3>
            <div class="metric-value">{metrics.total_examples}</div>
            <div class="metric-subtitle">Validation set size</div>
        </div>

        <div class="metric-card">
            <h3>Output Length (avg)</h3>
            <div class="metric-value">{metrics.teacher_avg_length}</div>
            <div class="metric-subtitle">
                Teacher: {metrics.teacher_avg_length} |
                Student: {metrics.student_avg_length}
            </div>
        </div>
    """
    return cards


def _build_field_comparison_html(example) -> str:
    """Build HTML for field-by-field JSON comparison if applicable."""
    if not example.is_json_output:
        return ""

    if not example.student_field_matches and not example.base_field_matches:
        return ""

    html = '<div class="comparison-section-title" style="margin-top: 20px;">Field Comparison</div>'
    html += '<div class="field-comparison-container">'

    # Fine-tuned field matches
    if example.student_field_matches:
        html += '<div class="field-group">'
        html += (
            '<div class="field-group-title">🎯 Fine-Tuned Model Fields</div>'
        )
        for field, matches in example.student_field_matches.items():
            status = "✓" if matches else "✗"
            badge_class = "field-match" if matches else "field-mismatch"
            html += (
                f'<div class="field-row {badge_class}">'
                f'{status} <span class="field-name">{_escape_html(field)}</span>'
                f'</div>'
            )
        html += "</div>"

    # Base model field matches
    if example.base_field_matches:
        html += '<div class="field-group">'
        html += '<div class="field-group-title">📦 Base Model Fields</div>'
        for field, matches in example.base_field_matches.items():
            status = "✓" if matches else "✗"
            badge_class = "field-match" if matches else "field-mismatch"
            html += (
                f'<div class="field-row {badge_class}">'
                f'{status} <span class="field-name">{_escape_html(field)}</span>'
                f'</div>'
            )
        html += "</div>"

    html += "</div>"
    return html


def _build_comparison_cards(examples) -> str:
    """Build HTML for individual comparison cards."""
    cards = []

    for i, example in enumerate(examples):
        is_match = example.exact_match
        match_class = "match" if is_match else "mismatch"
        match_badge = (
            '<span class="match-badge">✓ Exact Match</span>'
            if is_match
            else '<span class="mismatch-badge">✗ Mismatch</span>'
        )

        # Truncate input for display
        input_display = (
            example.input[:80] + "..."
            if len(example.input) > 80
            else example.input
        )

        # Base model thinking/output
        base_thinking_html = (
            f'<div class="comparison-text">'
            f'{_escape_html(example.base_thinking)}</div>'
            if example.base_thinking.strip()
            else '<div class="comparison-text empty">(No thinking)</div>'
        )
        base_output_html = _escape_html(example.base_output)

        # Fine-tuned model thinking/output
        finetuned_thinking_html = (
            f'<div class="comparison-text">'
            f'{_escape_html(example.student_thinking)}</div>'
            if example.student_thinking.strip()
            else '<div class="comparison-text empty">(No thinking)</div>'
        )
        finetuned_output_html = _escape_html(example.student_output)

        # Ground truth thinking/output
        ground_truth_thinking_html = (
            f'<div class="comparison-text">'
            f'{_escape_html(example.teacher_thinking)}</div>'
            if example.teacher_thinking.strip()
            else '<div class="comparison-text empty">(No thinking)</div>'
        )
        ground_truth_output_html = _escape_html(example.teacher_output)

        # Build metrics badges for each model
        base_badge = (
            '<span class="match-badge">✓ Match</span>'
            if example.base_exact_match
            else '<span class="mismatch-badge">✗ No Match</span>'
        )
        finetuned_badge = (
            '<span class="match-badge">✓ Match</span>'
            if example.exact_match
            else '<span class="mismatch-badge">✗ No Match</span>'
        )

        card_html = f"""
        <div class="comparison-card {match_class}" id="card-{i}">
            <div class="comparison-header" onclick="toggleDetails({i})">
                <div class="comparison-title">{_escape_html(input_display)}</div>
                {match_badge}
                <span class="toggle-arrow" id="arrow-{i}">▼</span>
            </div>

            <div class="comparison-content" id="content-{i}">
                <!-- Input -->
                <div class="comparison-section-title">Input</div>
                <div class="comparison-input">{_escape_html(example.input)}</div>

                <!-- Thinking (3 columns) -->
                <div class="comparison-section-title" style="margin-top: 20px;">
                    Thinking
                </div>
                <div class="comparison-grid-3col">
                    <div>
                        <div class="model-label">
                            📦 Base Model
                        </div>
                        {base_thinking_html}
                    </div>
                    <div>
                        <div class="model-label">
                            🎯 Fine-Tuned Model
                        </div>
                        {finetuned_thinking_html}
                    </div>
                    <div>
                        <div class="model-label">
                            ✨ Ground Truth
                        </div>
                        {ground_truth_thinking_html}
                    </div>
                </div>

                <!-- Outputs (3 columns) -->
                <div class="comparison-section-title" style="margin-top: 20px;">
                    Outputs
                </div>
                <div class="comparison-grid-3col">
                    <div>
                        <div class="model-label">
                            📦 Base Model {base_badge}
                        </div>
                        <div class="comparison-text">
                            {base_output_html}
                        </div>
                        <div class="metric-small">
                            Similarity: {example.base_similarity:.2f}
                        </div>
                    </div>
                    <div>
                        <div class="model-label">
                            🎯 Fine-Tuned Model {finetuned_badge}
                        </div>
                        <div class="comparison-text">
                            {finetuned_output_html}
                        </div>
                        <div class="metric-small">
                            Similarity: {example.similarity_score:.2f}
                        </div>
                    </div>
                    <div>
                        <div class="model-label">
                            ✨ Ground Truth
                        </div>
                        <div class="comparison-text">
                            {ground_truth_output_html}
                        </div>
                    </div>
                </div>

                <!-- Field-by-Field Comparison (if JSON) -->
                {_build_field_comparison_html(example)}
            </div>
        </div>
        """
        cards.append(card_html)

    return "\n".join(cards)


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    text = text or ""
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    text = text.replace('"', "&quot;")
    text = text.replace("'", "&#39;")
    return text
